script: "bundle exec rspec"
cache: bundler
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6.1
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
